[workspace]
members = ["crates/iron-core", "crates/iron-desktop", "crates/iron-cli", "tests/vm/ping-pong"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.metadata.crane]
name = "iron"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
data-encoding = "2"
dashmap = "6"
etherparse = "0.19"
futures = "0.3"
hex = "0.4"
hickory-client = "0.25"
hickory-proto = "0.25"
iroh = "1.0.0-rc.0"
iron-core = { path = "crates/iron-core" }
iron-desktop = { path = "crates/iron-desktop" }
nix = { version = "0.31", features = ["user"] }
postcard = { version = "1", features = ["alloc"] }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tun = { version = "0.8", features = ["async"] }
url = "2"
