//! Firewall with device ownership claims
//!
//! Implements a whitelist-based firewall that allows users to trust person identities
//! as well as individual devices. This provides a two-tier key system:
//! - **Person keys**: Long-term identity keys representing humans
//! - **Device keys**: Ephemeral keys (iroh EndpointId) for specific devices
//!
//! # Overview
//!
//! Instead of whitelisting each device individually, users can trust a person's
//! identity key. When that person adds new devices, they sign an ownership claim
//! that proves the device belongs to them. The firewall verifies these claims
//! and caches verified devices for performance.
//!
//! # Security Model
//!
//! - Person keys are long-lived Ed25519 keypairs
//! - Device ownership claims are signed by person keys
//! - Claims have expiration dates (default: 1 year)
//! - Verification results are cached persistently
//! - Manual revocation supported by removing person from whitelist

use anyhow::{Context, Result};
use iroh::EndpointId;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// A person's long-term identity key
///
/// This is separate from device keys and represents a human identity.
/// Person keys are Ed25519 keypairs used to sign ownership claims for devices.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PersonKey {
    /// Ed25519 public key (32 bytes)
    /// Users exchange and whitelist these keys
    #[serde(with = "serde_bytes")]
    public_key: [u8; 32],
}

impl PersonKey {
    /// Create a new PersonKey from raw bytes
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self { public_key: bytes }
    }

    /// Get the raw bytes of the public key
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.public_key
    }

    /// Verify a signature on a message
    pub fn verify(&self, message: &[u8], signature: &[u8; 64]) -> bool {
        use ed25519_dalek::{Signature, Verifier, VerifyingKey};

        let Ok(verifying_key) = VerifyingKey::from_bytes(&self.public_key) else {
            return false;
        };

        let sig = Signature::from_bytes(signature);
        verifying_key.verify(message, &sig).is_ok()
    }

    /// Convert to hex string for display
    pub fn to_hex(&self) -> String {
        hex::encode(self.public_key)
    }

    /// Parse from hex string
    pub fn from_hex(s: &str) -> Result<Self> {
        let bytes = hex::decode(s).context("Invalid hex string")?;
        if bytes.len() != 32 {
            anyhow::bail!(
                "Invalid person key length: expected 32 bytes, got {}",
                bytes.len()
            );
        }
        let mut array = [0u8; 32];
        array.copy_from_slice(&bytes);
        Ok(Self::from_bytes(array))
    }
}

/// A person's private key for signing ownership claims
#[derive(Clone)]
pub struct PersonSecretKey {
    /// Ed25519 secret key (32 bytes seed)
    secret_key: [u8; 32],
}

impl PersonSecretKey {
    /// Generate a new random person key
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut secret_key = [0u8; 32];
        rand::rng().fill_bytes(&mut secret_key);
        Self { secret_key }
    }

    /// Create from raw bytes
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self { secret_key: bytes }
    }

    /// Get the public key
    pub fn public_key(&self) -> PersonKey {
        use ed25519_dalek::SigningKey;
        let signing_key = SigningKey::from_bytes(&self.secret_key);
        PersonKey::from_bytes(signing_key.verifying_key().to_bytes())
    }

    /// Sign a message
    pub fn sign(&self, message: &[u8]) -> [u8; 64] {
        use ed25519_dalek::{Signer, SigningKey};
        let signing_key = SigningKey::from_bytes(&self.secret_key);
        signing_key.sign(message).to_bytes()
    }

    /// Convert to hex string
    pub fn to_hex(&self) -> String {
        hex::encode(self.secret_key)
    }

    /// Parse from hex string
    pub fn from_hex(s: &str) -> Result<Self> {
        let bytes = hex::decode(s).context("Invalid hex string")?;
        if bytes.len() != 32 {
            anyhow::bail!(
                "Invalid secret key length: expected 32 bytes, got {}",
                bytes.len()
            );
        }
        let mut array = [0u8; 32];
        array.copy_from_slice(&bytes);
        Ok(Self::from_bytes(array))
    }
}

/// A device's identity (what we currently call EndpointId)
///
/// This is the iroh EndpointId that identifies a specific device.
/// These can be rotated or changed without affecting the person's identity.
pub type DeviceKey = EndpointId;

/// Proof that a device is owned by a person
///
/// This is generated by the person and carried by the device.
/// The signature proves the person key holder authorized this device.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct OwnershipClaim {
    /// The person who owns this device
    pub person_key: PersonKey,

    /// The device being claimed
    pub device_key: DeviceKey,

    /// Signature: sign(person_key || device_key, person_private_key)
    /// This proves the person key holder authorized this device
    #[serde(with = "serde_bytes")]
    pub signature: [u8; 64],

    /// Timestamp when claim was created (Unix timestamp in seconds)
    pub created_at: u64,

    /// Expiry timestamp (Unix timestamp in seconds)
    pub expires_at: u64,
}

impl OwnershipClaim {
    /// Create a new ownership claim
    pub fn new(
        person_secret: &PersonSecretKey,
        device_key: DeviceKey,
        validity_seconds: u64,
    ) -> Self {
        let person_key = person_secret.public_key();
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        // Create the message to sign: "iron:ownership:" + device_key
        let message = format!("iron:ownership:{}", device_key);
        let signature = person_secret.sign(message.as_bytes());

        Self {
            person_key,
            device_key,
            signature,
            created_at: now,
            expires_at: now + validity_seconds,
        }
    }

    /// Verify the signature on this claim
    pub fn verify_signature(&self) -> bool {
        let message = format!("iron:ownership:{}", self.device_key);
        self.person_key.verify(message.as_bytes(), &self.signature)
    }

    /// Check if the claim has expired
    pub fn is_expired(&self) -> bool {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        now > self.expires_at
    }

    /// Verify the claim (signature + expiry)
    pub fn verify(&self) -> Result<()> {
        if self.is_expired() {
            anyhow::bail!("Ownership claim expired");
        }

        if !self.verify_signature() {
            anyhow::bail!("Invalid signature on ownership claim");
        }

        Ok(())
    }
}

/// Firewall action (currently only Accept for whitelist-based approach)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum FirewallAction {
    /// Accept packets from this source
    Accept,
}

/// Source of a packet for policy matching
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum PacketSource {
    /// Match by person key (by name from trusted_persons)
    Person(String), // references TrustedPerson.name

    /// Match by specific device EndpointId
    Peer(EndpointId),
}

/// A trusted person entry in the firewall configuration
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TrustedPerson {
    /// User-provided name (used as identifier in policies)
    pub name: String,

    /// Optional user comment
    pub comment: Option<String>,

    /// Ed25519 public key
    pub key: PersonKey,
}

/// Firewall policy (whitelist rule)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FirewallPolicy {
    /// Action to take (currently only Accept)
    pub action: FirewallAction,

    /// Source to match
    pub source: PacketSource,
}

/// Firewall configuration for a node
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FirewallConfig {
    /// Whether the firewall is enabled
    pub enabled: bool,

    /// List of trusted persons
    pub trusted_persons: Vec<TrustedPerson>,

    /// Firewall policies (whitelist rules)
    pub policies: Vec<FirewallPolicy>,

    /// Cache of verified devices (device_key -> person_key)
    /// Persisted to disk for performance
    #[serde(skip)]
    pub verified_devices: HashMap<DeviceKey, PersonKey>,
}

impl Default for FirewallConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            trusted_persons: Vec::new(),
            policies: Vec::new(),
            verified_devices: HashMap::new(),
        }
    }
}

impl FirewallConfig {
    /// Create a new firewall configuration
    pub fn new() -> Self {
        Self::default()
    }

    /// Verify an ownership claim and check if the person is trusted
    pub fn verify_claim(&mut self, claim: &OwnershipClaim) -> Result<bool> {
        // 1. Verify signature and expiry
        claim.verify()?;

        // 2. Check if person is trusted (look up by key in trusted_persons)
        let is_trusted = self
            .trusted_persons
            .iter()
            .any(|p| p.key == claim.person_key);

        if !is_trusted {
            return Ok(false); // Valid claim, but person not trusted
        }

        // 3. Cache the verified device
        self.verified_devices
            .insert(claim.device_key, claim.person_key.clone());

        Ok(true)
    }

    /// Check if a device is allowed to communicate
    pub fn is_device_allowed(&self, device_key: &DeviceKey) -> bool {
        if !self.enabled {
            return true; // Firewall disabled, allow all
        }

        self.verified_devices.contains_key(device_key)
    }

    /// Add a trusted person
    pub fn add_person(&mut self, person: TrustedPerson) {
        self.trusted_persons.push(person);
    }

    /// Remove a trusted person by name
    pub fn remove_person(&mut self, name: &str) -> bool {
        if let Some(pos) = self.trusted_persons.iter().position(|p| p.name == name) {
            let person = self.trusted_persons.remove(pos);
            // Also remove all verified devices owned by this person
            self.verified_devices.retain(|_, pk| pk != &person.key);
            true
        } else {
            false
        }
    }

    /// Get a person by name
    pub fn get_person(&self, name: &str) -> Option<&TrustedPerson> {
        self.trusted_persons.iter().find(|p| p.name == name)
    }

    /// Get the path to the firewall config file
    fn config_path() -> Result<PathBuf> {
        let home = std::env::var("HOME").context("HOME environment variable not set")?;
        Ok(PathBuf::from(home).join(".config/iron/firewall.json"))
    }

    /// Get the path to the verified devices cache
    fn cache_path() -> Result<PathBuf> {
        let home = std::env::var("HOME").context("HOME environment variable not set")?;
        Ok(PathBuf::from(home).join(".config/iron/firewall_cache.json"))
    }

    /// Load firewall configuration from disk
    pub fn load() -> Result<Self> {
        let config_path = Self::config_path()?;

        if !config_path.exists() {
            return Ok(Self::default());
        }

        let json = fs::read_to_string(&config_path).context("Failed to read firewall config")?;

        let mut config: Self =
            serde_json::from_str(&json).context("Failed to parse firewall config")?;

        // Load verified devices cache separately
        let cache_path = Self::cache_path()?;
        if cache_path.exists() {
            let cache_json =
                fs::read_to_string(&cache_path).context("Failed to read firewall cache")?;
            config.verified_devices =
                serde_json::from_str(&cache_json).context("Failed to parse firewall cache")?;
        }

        Ok(config)
    }

    /// Save firewall configuration to disk
    pub fn save(&self) -> Result<()> {
        let config_path = Self::config_path()?;

        // Create directory if it doesn't exist
        if let Some(dir) = config_path.parent() {
            fs::create_dir_all(dir).context("Failed to create config directory")?;

            // Set directory permissions to 0700 (owner only)
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let mut perms = fs::metadata(dir)?.permissions();
                perms.set_mode(0o700);
                fs::set_permissions(dir, perms)?;
            }
        }

        // Save main config (without verified_devices cache)
        let json =
            serde_json::to_string_pretty(self).context("Failed to serialize firewall config")?;
        fs::write(&config_path, json).context("Failed to write firewall config")?;

        // Set file permissions to 0600 (owner read/write only)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&config_path)?.permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&config_path, perms)?;
        }

        // Save verified devices cache separately
        self.save_cache()?;

        Ok(())
    }

    /// Save only the verified devices cache
    pub fn save_cache(&self) -> Result<()> {
        let cache_path = Self::cache_path()?;

        // Create directory if it doesn't exist (usually already exists)
        if let Some(dir) = cache_path.parent() {
            fs::create_dir_all(dir).context("Failed to create config directory")?;
        }

        let cache_json = serde_json::to_string_pretty(&self.verified_devices)
            .context("Failed to serialize firewall cache")?;
        fs::write(&cache_path, cache_json).context("Failed to write firewall cache")?;

        // Set file permissions to 0600 (owner read/write only)
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&cache_path)?.permissions();
            perms.set_mode(0o600);
            fs::set_permissions(&cache_path, perms)?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_person_key_from_bytes() {
        let bytes = [42u8; 32];
        let key = PersonKey::from_bytes(bytes);
        assert_eq!(key.as_bytes(), &bytes);
    }

    #[test]
    fn test_person_key_hex() {
        let bytes = [42u8; 32];
        let key = PersonKey::from_bytes(bytes);
        let hex = key.to_hex();
        let parsed = PersonKey::from_hex(&hex).unwrap();
        assert_eq!(key, parsed);
    }

    #[test]
    fn test_person_secret_key_generation() {
        let key1 = PersonSecretKey::generate();
        let key2 = PersonSecretKey::generate();
        // Different keys should be generated
        assert_ne!(key1.to_hex(), key2.to_hex());
    }

    #[test]
    fn test_sign_and_verify() {
        let secret = PersonSecretKey::generate();
        let public = secret.public_key();
        let message = b"test message";
        let signature = secret.sign(message);

        assert!(public.verify(message, &signature));
        assert!(!public.verify(b"different message", &signature));
    }

    #[test]
    fn test_ownership_claim_creation() {
        let person_secret = PersonSecretKey::generate();
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        let claim = OwnershipClaim::new(&person_secret, device_key, 3600);

        assert_eq!(claim.device_key, device_key);
        assert_eq!(claim.person_key, person_secret.public_key());
        assert!(claim.verify_signature());
        assert!(!claim.is_expired());
    }

    #[test]
    fn test_ownership_claim_expiry() {
        let person_secret = PersonSecretKey::generate();
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        // Create claim with 1 second validity
        let claim = OwnershipClaim::new(&person_secret, device_key, 1);

        // Should not be expired immediately
        assert!(!claim.is_expired());

        // Wait 2 seconds for it to expire
        std::thread::sleep(std::time::Duration::from_secs(2));
        assert!(claim.is_expired());
    }

    #[test]
    fn test_firewall_config_default() {
        let config = FirewallConfig::default();
        assert!(!config.enabled);
        assert_eq!(config.trusted_persons.len(), 0);
        assert_eq!(config.policies.len(), 0);
    }

    #[test]
    fn test_firewall_add_remove_person() {
        let mut config = FirewallConfig::new();
        let person_key = PersonSecretKey::generate().public_key();

        let person = TrustedPerson {
            name: "alice".to_string(),
            comment: Some("Test person".to_string()),
            key: person_key.clone(),
        };

        config.add_person(person);
        assert_eq!(config.trusted_persons.len(), 1);
        assert!(config.get_person("alice").is_some());

        assert!(config.remove_person("alice"));
        assert_eq!(config.trusted_persons.len(), 0);
        assert!(config.get_person("alice").is_none());
    }

    #[test]
    fn test_firewall_verify_claim() {
        let mut config = FirewallConfig::new();
        config.enabled = true;

        let person_secret = PersonSecretKey::generate();
        let person_key = person_secret.public_key();
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        // Add person to trusted list
        config.add_person(TrustedPerson {
            name: "bob".to_string(),
            comment: None,
            key: person_key.clone(),
        });

        // Create and verify claim
        let claim = OwnershipClaim::new(&person_secret, device_key, 3600);
        let result = config.verify_claim(&claim);

        assert!(result.is_ok());
        assert!(result.unwrap()); // Person is trusted
        assert!(config.verified_devices.contains_key(&device_key));
    }

    #[test]
    fn test_firewall_untrusted_person() {
        let mut config = FirewallConfig::new();
        config.enabled = true;

        let person_secret = PersonSecretKey::generate();
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        // Don't add person to trusted list
        let claim = OwnershipClaim::new(&person_secret, device_key, 3600);
        let result = config.verify_claim(&claim);

        assert!(result.is_ok());
        assert!(!result.unwrap()); // Person not trusted
        assert!(!config.verified_devices.contains_key(&device_key));
    }

    #[test]
    fn test_firewall_disabled_allows_all() {
        let config = FirewallConfig::new(); // disabled by default
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        assert!(config.is_device_allowed(&device_key));
    }

    #[test]
    fn test_config_persistence() {
        use tempfile::TempDir;
        let temp_dir = TempDir::new().unwrap();

        // Override HOME to use temp directory
        let home_path = temp_dir.path().to_str().unwrap();
        unsafe {
            std::env::set_var("HOME", home_path);
        }

        let mut config = FirewallConfig::new();
        config.enabled = true;

        let person_key = PersonSecretKey::generate().public_key();
        config.add_person(TrustedPerson {
            name: "test_person".to_string(),
            comment: Some("Test".to_string()),
            key: person_key.clone(),
        });

        // Save config
        config.save().unwrap();

        // Load config
        let loaded = FirewallConfig::load().unwrap();
        assert_eq!(loaded.enabled, true);
        assert_eq!(loaded.trusted_persons.len(), 1);
        assert_eq!(loaded.trusted_persons[0].name, "test_person");
    }

    #[test]
    fn test_cache_persistence() {
        use tempfile::TempDir;
        let temp_dir = TempDir::new().unwrap();

        // Override HOME to use temp directory
        let home_path = temp_dir.path().to_str().unwrap();
        unsafe {
            std::env::set_var("HOME", home_path);
        }

        let mut config = FirewallConfig::new();
        let person_key = PersonSecretKey::generate().public_key();
        let device_key = iroh::SecretKey::generate(&mut rand::rng()).public();

        config
            .verified_devices
            .insert(device_key, person_key.clone());

        // Save cache
        config.save_cache().unwrap();

        // Load config (which includes cache)
        let loaded = FirewallConfig::load().unwrap();
        assert!(loaded.verified_devices.contains_key(&device_key));
    }
}
